Global:
  use_gpu: false
  save_model_dir: ./weights/
  epoch_num: 10
  use_checkpoints: false
  checkpoint_dir: ./weights/pytorch_20230409_001728.pth

Architecture:
  Backbone:
    name: ResNet18
    num_classes: 10

Optimizer:
  name: Adam
  learning_rate: 1e-3

Loss:
  name: CE

Dataloader:
  imgs_size: 32
  test_size: 0.3
  batch_size: 64
  shuffle: true

Train:
  dataset: NumberDataset
  data_dir: ../../Datasets/Classification/dataset/

FeatureExtracter:
  Shape:
    width: 450
    height: 450
  size_image: 32
  model_dir: ./weights/pytorch_20230522_025336.pth
  probability_threshold: 0.98

GUI:
  name: Sudoku
  window_size: 1280x720
  canvas_size: 510
