Global:
  use_gpu: true
  save_model_dir: ./mode_weight/
  epoch_num: 5
  num_classes: 10

Architecture:
  Backbone:
    name: ResNet18

Optimizer:
  name: Adam
  learning_rate: 1e-4

Dataloader:
  imgs_size: 32
  test_size: 0.2
  batch_size: 32
  shuffle: true

Train:
  dataset: NumberDataset
  data_dir: ./train_data/number_classifer/

  

